language: go

go:
    - "1.9"
    - "1.10"
    - "1.11"
    - master

os:
  - linux

before_install:
    - go get golang.org/x/lint/golint
    - go get -d ./...

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update    ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo modprobe nf_conntrack ; fi

script:
    - go vet ./...
    - golint -set_exit_status ./...
    - go test -v -race ./...
    - ping -c 5 1.1.1.1
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo lsmod; fi
