language: go

go:
    - "1.9"
    - "1.10"
    - "1.11.x"
    - master

os:
  - linux

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update    ; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo modprobe nf_conntrack ; fi
    - go get golang.org/x/lint/golint
    - go get -d ./...

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo iptables -I OUTPUT -p icmp -j NFLOG --nflog-group 100 ; fi

script:
    - go vet ./...
    - golint -set_exit_status ./...
    - go test -v -race ./...
    - go test -c -tags integration .
    - ping -c 30 -i 2 1.1.1.1 &
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./go-nflog.test -test.v ; fi
